[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.32.1"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "5b702ec346491acf7a614e4269a2eec266558b4c"}
