[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.27.0"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "18804b20bf5c73526837765e3c8ee38591acfb18"}
