[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.20.0"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "ac058890df4ed6ffd40230292349c71f1b2d5748"}
