[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.35.1"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "3f7776136e1bf0310cb01c299d23b106ef2e2016"}
