[package]
name = "tuto"
version = "0.1"
lean_version = "leanprover-community/lean:3.24.0"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "cc6f039ffae734d113b3bcf81eae1581d0d60758"}
